//! Frozen owning-repository probe: --capabilities, schema 1, version, codex_exec.
use super::super::recipe_runner::ensure_recipe_runner;
use crate::test_support::{EnvGuard, home_env_lock};
use std::fs;
use std::os::unix::fs::PermissionsExt;

fn probe_fixture(stdout: &str, exit: i32, compatible: bool) {
    let _lock = home_env_lock().lock().unwrap_or_else(|p| p.into_inner());
    let dir = tempfile::tempdir().unwrap();
    let binary = dir.path().join("recipe-runner-rs");
    let output = dir.path().join("probe.json");
    let calls = dir.path().join("calls");
    fs::write(&output, stdout).unwrap();
    // Fixture paths are generated by tempfile, not caller-controlled shell strings.
    fs::write(
        &binary,
        format!(
            "#!/bin/sh\nprintf '%s\\n' \"$*\" >> '{}'\ncat '{}'\nexit {exit}\n",
            calls.display(),
            output.display()
        ),
    )
    .unwrap();
    fs::set_permissions(&binary, fs::Permissions::from_mode(0o700)).unwrap();
    let _env = EnvGuard::set([
        ("AMPLIHACK_AGENT_BINARY", "codex"),
        ("HOME", dir.path().to_str().unwrap()),
        ("CARGO_HOME", dir.path().to_str().unwrap()),
        ("RECIPE_RUNNER_RS_PATH", binary.to_str().unwrap()),
        ("AMPLIHACK_SKIP_RECIPE_RUNNER_INSTALL", "1"),
    ]);
    let before = fs::read(&binary).unwrap();
    let result = ensure_recipe_runner();
    assert_eq!(
        fs::read(&binary).unwrap(),
        before,
        "explicit runner must never be replaced"
    );
    assert_eq!(
        result.is_ok(),
        compatible,
        "probe acceptance mismatch: {result:?}"
    );
    assert_eq!(
        fs::read_to_string(calls).unwrap(),
        "--capabilities\n",
        "presence/version alone is insufficient"
    );
    if let Err(error) = result {
        let message = format!("{error:#}");
        assert!(
            message.contains("RECIPE_RUNNER_RS_PATH"),
            "explicit remediation: {message}"
        );
    }
}
#[test]
fn codex_runner_accepts_newer_custom_version_and_extra_capabilities() {
    probe_fixture(
        r#"{"schema_version":1,"version":"99.0.0-custom","capabilities":["future","codex_exec"],"extra":true}"#,
        0,
        true,
    );
}
#[test]
fn codex_runner_rejects_legacy_presence_only_binary() {
    probe_fixture("", 0, false);
}
#[test]
fn codex_runner_rejects_missing_capability() {
    probe_fixture(
        r#"{"schema_version":1,"version":"1","capabilities":["claude"]}"#,
        0,
        false,
    );
}
#[test]
fn codex_runner_rejects_unknown_major() {
    probe_fixture(
        r#"{"schema_version":2,"version":"1","capabilities":["codex_exec"]}"#,
        0,
        false,
    );
}
#[test]
fn codex_runner_rejects_invalid_json() {
    probe_fixture("not json", 0, false);
}
#[test]
fn codex_runner_rejects_failed_probe_even_with_valid_json() {
    probe_fixture(
        r#"{"schema_version":1,"version":"1","capabilities":["codex_exec"]}"#,
        2,
        false,
    );
}

#[test]
fn legacy_custom_runner_is_accepted_only_for_non_codex_provider() {
    let _lock = home_env_lock().lock().unwrap_or_else(|p| p.into_inner());
    let dir = tempfile::tempdir().unwrap();
    let binary = dir.path().join("recipe-runner-rs");
    fs::write(&binary, "#!/bin/sh\nexit 19\n").unwrap();
    fs::set_permissions(&binary, fs::Permissions::from_mode(0o700)).unwrap();
    let _env = EnvGuard::set([("RECIPE_RUNNER_RS_PATH", binary.to_str().unwrap())]);
    for provider in ["claude", "copilot"] {
        crate::freshness::with_provider(provider, || ensure_recipe_runner().unwrap());
    }
    assert!(crate::freshness::with_provider("codex", ensure_recipe_runner).is_err());
}
