//! Auto-documentation generation for agent bundles.
//!
//! Generates `INSTRUCTIONS.md` with installation, usage, testing, and
//! troubleshooting content for a packaged agent bundle.

/// Metadata required to generate documentation.
#[derive(Debug, Clone)]
pub struct BundleDocMeta {
    pub name: String,
    pub version: String,
    pub id: String,
    pub description: String,
    pub agent_names: Vec<String>,
    pub agent_roles: Vec<String>,
    pub created_at: String,
}

/// Generate a complete `INSTRUCTIONS.md` for the bundle.
pub fn generate_instructions(meta: &BundleDocMeta) -> String {
    let agent_list: String = meta
        .agent_names
        .iter()
        .zip(meta.agent_roles.iter())
        .map(|(n, r)| format!("  - `{n}`: {r}"))
        .collect::<Vec<_>>()
        .join("\n");

    let first_agent = meta
        .agent_names
        .first()
        .map(|s| s.as_str())
        .unwrap_or("agent-name");

    format!(
        r#"# {name} - Usage Instructions

## Overview

{desc}

This bundle contains {count} agent(s) ready to use with Amplihack.

## Prerequisites

{prereq}

## Installation

### Option 1: Install from UVX Package

```bash
uvx install {name}-{version}.uvx
uvx run {name}-{version}.uvx
```

### Option 2: Install from Source

```bash
cd {name}
pip install -e .
```

### Option 3: Manual Integration

```bash
cp -r agents/ ~/.claude/agents/custom/
```

## Quick Start

```bash
amplihack agents list
```

## Agents Included

{agents}

## Testing

```bash
pytest tests/ -v
```

## Directory Structure

```
{name}/
├── agents/
├── tests/
├── docs/
├── config/
├── manifest.json
├── pyproject.toml
├── README.md
├── INSTRUCTIONS.md
├── repackage.sh
└── repackage.py
```

## Usage Examples

### Basic Agent Usage

```python
from {name} import get_agent

agent = get_agent("{first_agent}")
result = agent.process("your task here")
```

## Troubleshooting

{troubleshooting}

## Version Information

- Bundle: {name}
- Version: {version}
- Bundle ID: {id}
- Agents: {count}
- Python Requirement: >=3.11

---

Generated by Agent Bundle Generator
Bundle created: {created}
"#,
        name = meta.name,
        desc = meta.description,
        count = meta.agent_names.len(),
        prereq = generate_prerequisites_section(),
        agents = agent_list,
        version = meta.version,
        id = meta.id,
        first_agent = first_agent,
        troubleshooting = generate_troubleshooting_section(),
        created = meta.created_at,
    )
}

/// Generate the troubleshooting section.
pub fn generate_troubleshooting_section() -> String {
    r#"### Common Issues

**Issue: Agent not found**
```
Solution: Ensure agents are installed in correct directory
1. Check: ~/.claude/agents/custom/
2. Verify manifest.json is present
3. Restart Claude Code session
```

**Issue: Import errors**
```
Solution: Verify dependencies are installed
pip install -r requirements.txt
```

**Issue: Tests failing**
```
Solution: Check Python version and dependencies
python --version  # Should be 3.11+
pytest tests/ -v
```

**Issue: UVX installation fails**
```
Solution: Install uvx if not available
pip install uvx
```"#
        .into()
}

/// Generate the prerequisites section.
pub fn generate_prerequisites_section() -> String {
    r#"### Required

- Python >= 3.11
- Amplihack >= 1.0.0 (or Claude Code environment)

### Optional

- `uvx` - For UVX package installation
- `pytest` - For running tests
- `git` - For version control integration"#
        .into()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_meta() -> BundleDocMeta {
        BundleDocMeta {
            name: "my-bundle".into(),
            version: "2.0.0".into(),
            id: "abc-123".into(),
            description: "A great bundle".into(),
            agent_names: vec!["analyzer".into(), "builder".into()],
            agent_roles: vec!["Code analysis".into(), "Build automation".into()],
            created_at: "2025-01-01T00:00:00Z".into(),
        }
    }

    #[test]
    fn instructions_contain_bundle_name() {
        let md = generate_instructions(&sample_meta());
        assert!(md.contains("my-bundle"));
    }

    #[test]
    fn instructions_contain_agents() {
        let md = generate_instructions(&sample_meta());
        assert!(md.contains("`analyzer`"));
        assert!(md.contains("`builder`"));
    }

    #[test]
    fn instructions_contain_version() {
        let md = generate_instructions(&sample_meta());
        assert!(md.contains("2.0.0"));
    }

    #[test]
    fn troubleshooting_not_empty() {
        let ts = generate_troubleshooting_section();
        assert!(ts.contains("Agent not found"));
        assert!(ts.contains("Import errors"));
    }

    #[test]
    fn prerequisites_not_empty() {
        let prereq = generate_prerequisites_section();
        assert!(prereq.contains("Python >= 3.11"));
    }

    #[test]
    fn instructions_contain_created_at() {
        let md = generate_instructions(&sample_meta());
        assert!(md.contains("2025-01-01T00:00:00Z"));
    }

    #[test]
    fn empty_agents_still_works() {
        let meta = BundleDocMeta {
            name: "empty".into(),
            version: "0.1.0".into(),
            id: "x".into(),
            description: "no agents".into(),
            agent_names: vec![],
            agent_roles: vec![],
            created_at: "now".into(),
        };
        let md = generate_instructions(&meta);
        assert!(md.contains("0 agent(s)"));
        assert!(md.contains("agent-name")); // fallback name
    }
}
