//! Repackage script generation for agent bundles.
//!
//! Generates self-contained Bash and Python scripts that validate, test,
//! and rebuild a bundle distribution.

use crate::error::{GeneratorError, Result};

#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;
use std::path::Path;

/// Generate a Bash repackage script.
pub fn generate_bash_script(name: &str, version: &str) -> Result<String> {
    let safe_name = sanitize_bundle_name(name)?;
    let safe_version = sanitize_version(version)?;

    Ok(format!(
        r##"#!/usr/bin/env bash
# Repackage script for {safe_name}
# Generated by Agent Bundle Generator

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

BUNDLE_NAME="{safe_name}"
BUNDLE_VERSION="{safe_version}"
PACKAGE_NAME="${{BUNDLE_NAME}}-${{BUNDLE_VERSION}}"
OUTPUT_DIR="./dist"

log_info()  {{ echo -e "${{GREEN}}[INFO]${{NC}} $1"; }}
log_warn()  {{ echo -e "${{YELLOW}}[WARN]${{NC}} $1"; }}
log_error() {{ echo -e "${{RED}}[ERROR]${{NC}} $1"; }}

check_prerequisites() {{
    log_info "Checking prerequisites..."
    if ! command -v python3 &>/dev/null; then
        log_error "Python 3 not found"; exit 1
    fi
    log_info "Python version: $(python3 --version | cut -d' ' -f2)"
    command -v pytest &>/dev/null && log_info "pytest: $(pytest --version | head -1)" || log_warn "pytest not found"
    command -v uvx &>/dev/null && log_info "uvx: available" || log_warn "uvx not found"
}}

validate_structure() {{
    log_info "Validating bundle structure..."
    for dir in agents tests config; do
        [ -d "$dir" ] || {{ log_error "Missing directory: $dir"; exit 1; }}
    done
    for f in manifest.json README.md setup.py; do
        [ -f "$f" ] || {{ log_error "Missing file: $f"; exit 1; }}
    done
    python3 -c "import json; json.load(open('manifest.json'))" 2>/dev/null || {{ log_error "Invalid manifest.json"; exit 1; }}
    AGENT_COUNT=$(ls -1 agents/*.md 2>/dev/null | wc -l | tr -d ' ')
    log_info "Found $AGENT_COUNT agent(s)"
    [ "$AGENT_COUNT" -eq 0 ] && {{ log_error "No agents found"; exit 1; }}
    log_info "Structure validation: PASSED"
}}

run_tests() {{
    log_info "Running tests..."
    command -v pytest &>/dev/null || {{ log_warn "pytest not available"; return 0; }}
    [ -d "tests" ] && ls tests/*.py &>/dev/null || {{ log_warn "No tests found"; return 0; }}
    pytest tests/ -v --tb=short || {{ log_error "Tests: FAILED"; exit 1; }}
    log_info "Tests: PASSED"
}}

build_package() {{
    log_info "Building package..."
    mkdir -p "$OUTPUT_DIR"
    python3 setup.py sdist --dist-dir="$OUTPUT_DIR" >/dev/null 2>&1 && log_info "Source dist: CREATED" || log_warn "Source dist failed"
}}

calculate_checksums() {{
    log_info "Calculating checksums..."
    [ -d "$OUTPUT_DIR" ] && cd "$OUTPUT_DIR" && sha256sum * > SHA256SUMS 2>/dev/null; cd - >/dev/null
}}

print_summary() {{
    echo ""
    echo "========================================"
    echo "Repackaging Complete!"
    echo "Bundle: $BUNDLE_NAME  Version: $BUNDLE_VERSION"
    echo "========================================"
}}

main() {{
    echo "========================================"
    echo "Repackaging $BUNDLE_NAME v$BUNDLE_VERSION"
    echo "========================================"
    check_prerequisites; echo ""
    validate_structure; echo ""
    run_tests; echo ""
    build_package; echo ""
    calculate_checksums; echo ""
    print_summary
}}

main "$@"
"##
    ))
}

/// Generate a Python repackage script.
pub fn generate_python_script(name: &str, version: &str) -> Result<String> {
    let safe_name = sanitize_bundle_name(name)?;
    let safe_version = sanitize_version(version)?;

    Ok(format!(
        r#"#!/usr/bin/env python3
"""Repackage script for {safe_name}. Generated by Agent Bundle Generator."""

import hashlib, json, shutil, subprocess, sys
from pathlib import Path

BUNDLE_NAME = "{safe_name}"
BUNDLE_VERSION = "{safe_version}"

def log_info(msg):  print(f"\033[0;32m[INFO]\033[0m {{msg}}")
def log_warn(msg):  print(f"\033[1;33m[WARN]\033[0m {{msg}}")
def log_error(msg): print(f"\033[0;31m[ERROR]\033[0m {{msg}}")

def check_prerequisites():
    v = sys.version.split()[0]
    log_info(f"Python {{v}}")
    return True

def validate_structure():
    for d in ["agents", "tests", "config"]:
        if not Path(d).is_dir():
            log_error(f"Missing dir: {{d}}"); return False
    for f in ["manifest.json", "README.md", "setup.py"]:
        if not Path(f).is_file():
            log_error(f"Missing file: {{f}}"); return False
    return True

def run_tests():
    if not shutil.which("pytest"):
        log_warn("pytest not found"); return True
    r = subprocess.run(["pytest", "tests/", "-v", "--tb=short"])
    return r.returncode == 0

def build_package():
    dist = Path("./dist")
    dist.mkdir(exist_ok=True)
    subprocess.run([sys.executable, "setup.py", "sdist", f"--dist-dir={{dist}}"])

def calculate_checksums():
    dist = Path("./dist")
    if not dist.exists(): return
    lines = []
    for p in sorted(dist.glob("*")):
        if p.is_file() and p.name != "SHA256SUMS":
            h = hashlib.sha256(p.read_bytes()).hexdigest()
            lines.append(f"{{h}}  {{p.name}}")
    if lines:
        (dist / "SHA256SUMS").write_text("\n".join(lines) + "\n")

def main():
    if not check_prerequisites(): sys.exit(1)
    if not validate_structure(): sys.exit(1)
    if not run_tests(): sys.exit(1)
    build_package()
    calculate_checksums()
    log_info("Repackaging complete!")

if __name__ == "__main__":
    main()
"#
    ))
}

/// Make a script file executable (Unix only; no-op on Windows).
///
/// # Errors
/// Returns an error if the path does not exist or `chmod` fails.
pub fn make_executable(path: &Path) -> std::io::Result<()> {
    if !path.exists() {
        return Err(std::io::Error::new(
            std::io::ErrorKind::NotFound,
            format!("Script not found: {}", path.display()),
        ));
    }
    #[cfg(unix)]
    {
        let mut perms = std::fs::metadata(path)?.permissions();
        let mode = perms.mode();
        perms.set_mode(mode | 0o111);
        std::fs::set_permissions(path, perms)?;
    }
    Ok(())
}

/// Sanitize a bundle name: only allow `[a-zA-Z0-9_-]`.
pub fn sanitize_bundle_name(name: &str) -> Result<String> {
    let sanitized: String = name.chars().filter(|c| c.is_alphanumeric() || *c == '-' || *c == '_').collect();
    if sanitized.is_empty() {
        return Err(GeneratorError::PackagingFailed(format!(
            "Bundle name contains no valid characters: {name}"
        )));
    }
    Ok(sanitized)
}

/// Sanitize a version string: only allow `[0-9.-]`.
pub fn sanitize_version(version: &str) -> Result<String> {
    let sanitized: String = version.chars().filter(|c| c.is_ascii_digit() || *c == '.' || *c == '-').collect();
    if sanitized.is_empty() {
        return Err(GeneratorError::PackagingFailed(format!(
            "Version contains no valid characters: {version}"
        )));
    }
    Ok(sanitized)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sanitize_name_ok() {
        assert_eq!(sanitize_bundle_name("my-bundle_1").unwrap(), "my-bundle_1");
    }

    #[test]
    fn sanitize_name_strips_bad() {
        assert_eq!(sanitize_bundle_name("a/b;c").unwrap(), "abc");
    }

    #[test]
    fn sanitize_name_empty_err() {
        assert!(sanitize_bundle_name("///").is_err());
    }

    #[test]
    fn sanitize_version_ok() {
        assert_eq!(sanitize_version("1.2.3-0").unwrap(), "1.2.3-0");
    }

    #[test]
    fn sanitize_version_strips() {
        assert_eq!(sanitize_version("v1.0").unwrap(), "1.0");
    }

    #[test]
    fn sanitize_version_empty_err() {
        assert!(sanitize_version("abc").is_err());
    }

    #[test]
    fn bash_script_contains_name() {
        let script = generate_bash_script("test-b", "1.0.0").unwrap();
        assert!(script.contains("test-b"));
        assert!(script.contains("1.0.0"));
        assert!(script.starts_with("#!/usr/bin/env bash"));
    }

    #[test]
    fn python_script_contains_name() {
        let script = generate_python_script("test-b", "2.0.0").unwrap();
        assert!(script.contains("test-b"));
        assert!(script.contains("2.0.0"));
        assert!(script.starts_with("#!/usr/bin/env python3"));
    }

    #[test]
    fn make_executable_missing_file() {
        let res = make_executable(Path::new("/nonexistent/script.sh"));
        assert!(res.is_err());
    }

    #[cfg(unix)]
    #[test]
    fn make_executable_sets_bits() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("test.sh");
        std::fs::write(&path, "#!/bin/bash").unwrap();
        make_executable(&path).unwrap();

        let perms = std::fs::metadata(&path).unwrap().permissions();
        assert_ne!(perms.mode() & 0o111, 0);
    }
}
