//! Generation of `~/.amplihack/signal-config.toml` for `amplihack signal setup`.
//!
//! The critical contract: this output is consumed **unchanged** by the existing
//! per-session channel, so it must resolve cleanly through the real
//! `amplihack_signal::config` loader. It reuses that loader's exact schema
//! (`endpoint`, `account`, `allowlist`) and fail-closed semantics.
//!
//! Single-number linked-device rule: the operator's phone replies arrive as the
//! account's **own synced messages**, so the account number must be on its own
//! allowlist — i.e. `allowlist = [account]` exactly. Emitting an empty or
//! wildcard allowlist is never done.

/// Render the onboarding config as a TOML string.
///
/// `endpoint` is the loopback `host:port` of the local signal-cli JSON-RPC
/// daemon; `account` is the linked E.164 number. The account is placed on its
/// own allowlist (the single-number linked-device rule). Values are TOML
/// basic-string escaped defensively; callers should still validate inputs via
/// [`super::validate`] before writing.
pub fn to_toml(endpoint: &str, account: &str) -> String {
    format!(
        "# amplihack Signal channel configuration.\n\
         # Generated by `amplihack signal setup` (issue #921). Safe to edit.\n\
         # Precedence is unchanged: environment variables override these values.\n\
         #\n\
         # `allowlist = [account]` is deliberate for the single-number\n\
         # linked-device setup: the operator's replies arrive as the account's\n\
         # own synced messages and must be accepted.\n\
         endpoint = \"{endpoint}\"\n\
         account = \"{account}\"\n\
         allowlist = [\"{account}\"]\n",
        endpoint = escape_basic(endpoint),
        account = escape_basic(account),
    )
}

/// Escape a value for a TOML basic string (`"..."`): backslash and double-quote
/// only — inputs are otherwise constrained to E.164 / `host:port` shapes.
fn escape_basic(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
