//! Documentation generator for agent bundles.
//!
//! Ported from `amplihack/bundle_generator/documentation_generator.py`.

use std::fmt::Write;

/// Lightweight description of a bundle for documentation.
#[derive(Debug, Clone)]
pub struct BundleInfo {
    pub name: String,
    pub version: String,
    pub description: String,
    pub id: String,
    pub agents: Vec<(String, String)>, // (name, role)
}

/// Documentation generator with stateless methods.
pub struct DocumentationGenerator;

impl DocumentationGenerator {
    /// Generate complete INSTRUCTIONS.md.
    pub fn generate_instructions(info: &BundleInfo) -> String {
        let agent_count = info.agents.len();
        let first_agent = info
            .agents
            .first()
            .map(|(n, _)| n.as_str())
            .unwrap_or("agent-name");
        let agent_list = if info.agents.is_empty() {
            "  - (no agents)".to_string()
        } else {
            info.agents
                .iter()
                .map(|(n, r)| format!("  - `{n}`: {r}"))
                .collect::<Vec<_>>()
                .join("\n")
        };
        let prereqs = Self::generate_prerequisites_section();
        let troubleshooting = Self::generate_troubleshooting_section();
        let name_mod = info.name.replace('-', "_");

        format!(
            "# {name} - Usage Instructions\n\n\
             ## Overview\n\n{desc}\n\n\
             This bundle contains {agent_count} agent(s) ready to use with Amplihack.\n\n\
             ## Prerequisites\n\n{prereqs}\n\n\
             ## Installation\n\n\
             ### Option 1: Install from UVX Package\n\n\
             ```bash\nuvx install {name}-{ver}.uvx\nuvx run {name}-{ver}.uvx\n```\n\n\
             ### Option 2: Install from Source\n\n\
             ```bash\ncd {name}\npip install -e .\n```\n\n\
             ### Option 3: Manual Integration\n\n\
             ```bash\ncp -r agents/ ~/.claude/agents/custom/\n```\n\n\
             ## Quick Start\n\n\
             ### Using with Amplihack\n\n\
             ```bash\namplihack agents list\n```\n\n\
             ### Using Agents Directly\n\n\
             Reference: `@agent:{first_agent}`\n\n\
             ## Agents Included\n\n{agent_list}\n\n\
             ## Configuration\n\n\
             Edit `config/bundle_config.json` to customize.\n\n\
             ## Testing\n\n\
             ```bash\npytest tests/\npytest -v tests/\n```\n\n\
             ## Directory Structure\n\n\
             ```\n{name}/\n\
             ├── agents/\n├── tests/\n├── docs/\n├── config/\n\
             ├── manifest.json\n├── README.md\n└── INSTRUCTIONS.md\n```\n\n\
             ## Usage Examples\n\n\
             ```python\n\
             from {name_mod} import get_agent\n\
             agent = get_agent(\"{first_agent}\")\n\
             result = agent.process(\"your task\")\n\
             ```\n\n\
             ## Troubleshooting\n\n{troubleshooting}\n\n\
             ## Version Information\n\n\
             - Bundle: {name}\n\
             - Version: {ver}\n\
             - Bundle ID: {id}\n\
             - Agents: {agent_count}\n\n\
             ---\n\nGenerated by Agent Bundle Generator\n",
            name = info.name,
            ver = info.version,
            desc = info.description,
            id = info.id,
        )
    }

    /// Prerequisites section content.
    pub fn generate_prerequisites_section() -> String {
        "### Required\n\n\
         - Python >= 3.11\n\
         - Amplihack >= 1.0.0 (or Claude Code environment)\n\n\
         ### Optional\n\n\
         - `uvx` - For UVX package installation\n\
         - `pytest` - For running tests\n\
         - `git` - For version control integration\n\n\
         ### Installation\n\n\
         ```bash\n\
         pip install amplihack pytest\n\
         pip install uvx\n\
         ```"
        .to_string()
    }

    /// Troubleshooting section with 6 common issues.
    pub fn generate_troubleshooting_section() -> String {
        "### Common Issues\n\n\
         **Issue: Agent not found**\n\
         Ensure agents are installed in ~/.claude/agents/custom/. \
         Verify manifest.json is present.\n\n\
         **Issue: Import errors**\n\
         Verify dependencies: `pip install -r requirements.txt`\n\n\
         **Issue: Tests failing**\n\
         Check Python version (3.11+) and dependencies: `pytest tests/ -v`\n\n\
         **Issue: UVX installation fails**\n\
         Install uvx: `pip install uvx`\n\n\
         **Issue: Permission denied when copying agents**\n\
         Use `sudo cp -r agents/ ~/.claude/agents/custom/` or adjust permissions.\n\n\
         **Issue: Agents not appearing in Claude Code**\n\
         Restart Claude Code and clear cache: `rm -rf ~/.claude/cache/`"
            .to_string()
    }

    /// API documentation section for a single agent.
    pub fn generate_api_docs(agent_name: &str, capabilities: &[String]) -> String {
        let mut out = format!("# API Reference: {agent_name}\n\n## Capabilities\n\n");
        if capabilities.is_empty() {
            let _ = writeln!(out, "- General processing");
        } else {
            for cap in capabilities {
                let _ = writeln!(out, "- `{cap}`");
            }
        }
        let _ = writeln!(
            out,
            "\n## Input Format\n\n\
             ```json\n{{\n  \"action\": \"<capability>\",\n  \"data\": {{}}\n}}\n```"
        );
        let _ = writeln!(
            out,
            "\n## Output Format\n\n\
             ```json\n{{\n  \"status\": \"success\",\n  \"result\": {{}}\n}}\n```"
        );
        out
    }

    /// Short installation guide for embedding in README.
    pub fn generate_install_guide(bundle_name: &str, version: &str) -> String {
        format!(
            "## Installation\n\n\
             ### Quick Install (UVX)\n\n\
             ```bash\nuvx install {bundle_name}-{version}.uvx\n```\n\n\
             ### From Source\n\n\
             ```bash\ncd {bundle_name}\npip install -e .\n```\n\n\
             ### Manual Copy\n\n\
             ```bash\ncp -r agents/ ~/.claude/agents/custom/\n```\n"
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_info() -> BundleInfo {
        BundleInfo {
            name: "test-bundle".to_string(),
            version: "1.0.0".to_string(),
            description: "A test bundle".to_string(),
            id: "abc-123".to_string(),
            agents: vec![
                ("scanner".to_string(), "Scans data".to_string()),
                ("analyzer".to_string(), "Analyzes results".to_string()),
            ],
        }
    }

    #[test]
    fn test_instructions_contains_name() {
        assert!(
            DocumentationGenerator::generate_instructions(&sample_info()).contains("test-bundle")
        );
    }

    #[test]
    fn test_instructions_contains_agents() {
        let doc = DocumentationGenerator::generate_instructions(&sample_info());
        assert!(doc.contains("`scanner`"));
        assert!(doc.contains("`analyzer`"));
    }

    #[test]
    fn test_instructions_key_sections() {
        let doc = DocumentationGenerator::generate_instructions(&sample_info());
        for section in &[
            "## Prerequisites",
            "## Installation",
            "## Quick Start",
            "## Agents Included",
            "## Testing",
            "## Directory Structure",
            "## Troubleshooting",
            "## Version Information",
        ] {
            assert!(doc.contains(section), "missing: {section}");
        }
    }

    #[test]
    fn test_empty_agents_fallback() {
        let info = BundleInfo {
            name: "empty".to_string(),
            version: "0.1.0".to_string(),
            description: "Empty".to_string(),
            id: "x".to_string(),
            agents: vec![],
        };
        let doc = DocumentationGenerator::generate_instructions(&info);
        assert!(doc.contains("agent-name"));
        assert!(doc.contains("0 agent(s)"));
    }

    #[test]
    fn test_prerequisites_section() {
        let s = DocumentationGenerator::generate_prerequisites_section();
        assert!(s.contains("Python >= 3.11"));
        assert!(s.contains("uvx"));
    }

    #[test]
    fn test_troubleshooting_has_six_issues() {
        let s = DocumentationGenerator::generate_troubleshooting_section();
        assert_eq!(s.matches("**Issue:").count(), 6);
    }

    #[test]
    fn test_api_docs() {
        let doc = DocumentationGenerator::generate_api_docs(
            "scanner",
            &["scan".to_string(), "index".to_string()],
        );
        assert!(doc.contains("`scan`"));
        assert!(doc.contains("`index`"));
    }

    #[test]
    fn test_api_docs_empty() {
        assert!(DocumentationGenerator::generate_api_docs("a", &[]).contains("General processing"));
    }

    #[test]
    fn test_install_guide() {
        let g = DocumentationGenerator::generate_install_guide("my-bundle", "2.0.0");
        assert!(g.contains("my-bundle-2.0.0.uvx"));
    }

    #[test]
    fn test_module_name_underscores() {
        let info = BundleInfo {
            name: "my-cool-bundle".to_string(),
            version: "1.0.0".to_string(),
            description: "Cool".to_string(),
            id: "x".to_string(),
            agents: vec![("a".to_string(), "r".to_string())],
        };
        assert!(DocumentationGenerator::generate_instructions(&info).contains("my_cool_bundle"));
    }
}
