//! Agent content generator — creates markdown agent files from requirements.
//!
//! Ported from `amplihack/bundle_generator/generator.py`.

use super::generator_templates as tpl;

/// Describes a single agent to generate.
#[derive(Debug, Clone)]
pub struct AgentRequirement {
    pub name: String,
    pub role: String,
    pub purpose: String,
    pub capabilities: Vec<String>,
    pub suggested_type: String,
    pub dependencies: Vec<String>,
}

/// Complexity level of the generation intent.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Complexity {
    Simple,
    Standard,
    Advanced,
}

impl Complexity {
    pub fn from_str_loose(s: &str) -> Self {
        match s {
            "simple" => Self::Simple,
            "advanced" | "complex" => Self::Advanced,
            _ => Self::Standard,
        }
    }
}

/// Output of generation.
#[derive(Debug, Clone)]
pub struct GeneratedContent {
    pub content: String,
    pub tests: Vec<String>,
    pub documentation: String,
}

/// Generates agent markdown files from requirements.
pub struct AgentGenerator {
    pub include_tests: bool,
    pub include_docs: bool,
}

impl Default for AgentGenerator {
    fn default() -> Self {
        Self {
            include_tests: true,
            include_docs: true,
        }
    }
}

impl AgentGenerator {
    pub fn new() -> Self {
        Self::default()
    }

    /// Generate content for a single agent.
    pub fn generate_agent(
        &self,
        req: &AgentRequirement,
        domain: &str,
        action: &str,
        complexity: Complexity,
    ) -> GeneratedContent {
        let display_name = tpl::titlecase_name(&req.name);
        let description = tpl::generate_description(req, domain, action);
        let capabilities = tpl::generate_capabilities(&req.capabilities);
        let responsibilities = tpl::generate_responsibilities(req, complexity);
        let implementation = tpl::generate_implementation(req, complexity);
        let philosophy = tpl::generate_philosophy();
        let error_handling = tpl::generate_error_handling();
        let performance = tpl::generate_performance(complexity);
        let dependencies = tpl::generate_dependencies(&req.dependencies);
        let examples = tpl::generate_examples(&req.name);
        let testing = tpl::generate_testing(req);

        let content = format!(
            "# {display_name}\n\n\
             {description}\n\n\
             ## Role\n\n\
             {role}\n\n\
             ## Model Configuration\n\n\
             Model: inherit\n\n\
             ## Capabilities\n\n\
             {capabilities}\n\n\
             ## Core Responsibilities\n\n\
             {responsibilities}\n\n\
             ## Implementation\n\n\
             {implementation}\n\n\
             ## Context and Philosophy\n\n\
             {philosophy}\n\n\
             ## Error Handling\n\n\
             {error_handling}\n\n\
             ## Performance Considerations\n\n\
             {performance}\n\n\
             ## Dependencies\n\n\
             {dependencies}\n\n\
             ## Example Usage\n\n\
             {examples}\n\n\
             ## Testing\n\n\
             {testing}\n\n\
             ---\n\
             Generated by Agent Bundle Generator v1.0.0\n",
            role = req.role,
        );

        let tests = if self.include_tests {
            vec![tpl::generate_test_file(req)]
        } else {
            Vec::new()
        };

        let documentation = if self.include_docs {
            tpl::generate_extended_docs(req)
        } else {
            String::new()
        };

        GeneratedContent {
            content,
            tests,
            documentation,
        }
    }

    /// Validate generated content, returning a list of issues (empty = valid).
    pub fn validate_content(content: &str) -> Vec<String> {
        let mut issues = Vec::new();
        if content.len() < 100 {
            issues.push("Content too short (< 100 chars)".to_string());
        }
        for section in &["## Role", "## Capabilities", "## Implementation"] {
            if !content.contains(section) {
                issues.push(format!("Missing required section: {section}"));
            }
        }
        if content.contains("TODO") || content.contains("PLACEHOLDER") {
            issues.push("Content contains placeholder text".to_string());
        }
        issues
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_req() -> AgentRequirement {
        AgentRequirement {
            name: "data-scanner".to_string(),
            role: "Scans and indexes data sources".to_string(),
            purpose: "Automatically discover and catalog data assets".to_string(),
            capabilities: vec!["scanning".to_string(), "indexing".to_string()],
            suggested_type: "specialized".to_string(),
            dependencies: vec!["core-lib".to_string()],
        }
    }

    #[test]
    fn test_generate_agent_has_required_sections() {
        let ag = AgentGenerator::new();
        let result = ag.generate_agent(
            &sample_req(),
            "data-processing",
            "create",
            Complexity::Standard,
        );
        for section in &[
            "## Role",
            "## Capabilities",
            "## Implementation",
            "## Testing",
            "## Error Handling",
        ] {
            assert!(result.content.contains(section), "missing: {section}");
        }
    }

    #[test]
    fn test_content_length() {
        let ag = AgentGenerator::new();
        let result = ag.generate_agent(
            &sample_req(),
            "data-processing",
            "create",
            Complexity::Standard,
        );
        assert!(result.content.len() > 500);
    }

    #[test]
    fn test_validate_passes() {
        let ag = AgentGenerator::new();
        let result = ag.generate_agent(
            &sample_req(),
            "data-processing",
            "create",
            Complexity::Standard,
        );
        assert!(AgentGenerator::validate_content(&result.content).is_empty());
    }

    #[test]
    fn test_validate_short() {
        let issues = AgentGenerator::validate_content("short");
        assert!(issues.iter().any(|i| i.contains("too short")));
    }

    #[test]
    fn test_validate_missing_sections() {
        let issues = AgentGenerator::validate_content(&"x".repeat(200));
        assert!(issues.iter().any(|i| i.contains("Role")));
    }

    #[test]
    fn test_validate_placeholder() {
        let content = format!(
            "## Role\n## Capabilities\n## Implementation\n{}TODO: finish",
            "x".repeat(200)
        );
        assert!(
            AgentGenerator::validate_content(&content)
                .iter()
                .any(|i| i.contains("placeholder"))
        );
    }

    #[test]
    fn test_tests_generated() {
        let ag = AgentGenerator::new();
        let result = ag.generate_agent(&sample_req(), "security", "create", Complexity::Simple);
        assert!(!result.tests.is_empty());
        assert!(result.tests[0].contains("test_agent_file_exists"));
    }

    #[test]
    fn test_tests_skipped() {
        let ag = AgentGenerator {
            include_tests: false,
            include_docs: false,
        };
        let result = ag.generate_agent(&sample_req(), "security", "create", Complexity::Simple);
        assert!(result.tests.is_empty());
        assert!(result.documentation.is_empty());
    }

    #[test]
    fn test_docs_generated() {
        let ag = AgentGenerator::new();
        let result = ag.generate_agent(
            &sample_req(),
            "data-processing",
            "create",
            Complexity::Standard,
        );
        assert!(result.documentation.contains("Extended Documentation"));
    }

    #[test]
    fn test_advanced_adds_responsibilities() {
        let ag = AgentGenerator::new();
        let result = ag.generate_agent(
            &sample_req(),
            "data-processing",
            "create",
            Complexity::Advanced,
        );
        assert!(result.content.contains("Optimization"));
    }

    #[test]
    fn test_simple_no_advanced_features() {
        let ag = AgentGenerator::new();
        let result = ag.generate_agent(
            &sample_req(),
            "data-processing",
            "create",
            Complexity::Simple,
        );
        assert!(!result.content.contains("### Advanced Features"));
    }

    #[test]
    fn test_no_deps_text() {
        let ag = AgentGenerator::new();
        let mut req = sample_req();
        req.dependencies.clear();
        let result = ag.generate_agent(&req, "general", "create", Complexity::Simple);
        assert!(
            result
                .content
                .contains("No external dependencies required.")
        );
    }

    #[test]
    fn test_empty_capabilities_fallback() {
        let ag = AgentGenerator::new();
        let mut req = sample_req();
        req.capabilities.clear();
        let result = ag.generate_agent(&req, "general", "create", Complexity::Simple);
        assert!(result.content.contains("General processing and analysis"));
    }

    #[test]
    fn test_complexity_from_str() {
        assert_eq!(Complexity::from_str_loose("simple"), Complexity::Simple);
        assert_eq!(Complexity::from_str_loose("advanced"), Complexity::Advanced);
        assert_eq!(Complexity::from_str_loose("complex"), Complexity::Advanced);
        assert_eq!(Complexity::from_str_loose("unknown"), Complexity::Standard);
    }

    #[test]
    fn test_no_placeholders_in_output() {
        let ag = AgentGenerator::new();
        let result = ag.generate_agent(&sample_req(), "security", "create", Complexity::Advanced);
        assert!(!result.content.contains("PLACEHOLDER"));
        assert!(!result.content.contains("TODO"));
    }
}
