//! Generated file content — Python, README, requirements, and YAML templates.

use super::AgentBundle;

pub(super) fn generate_main_py(bundle: &AgentBundle) -> String {
    let memory_import = if bundle.memory_enabled {
        "\ntry:\n    from amplihack_memory import MemoryConnector, ExperienceStore\nexcept ImportError:\n    print(\"Warning: amplihack-memory-lib not found. Memory features disabled.\")\n    MemoryConnector = None\n"
    } else {
        ""
    };

    format!(
        r#"#!/usr/bin/env python3
"""
{name} - Autonomous Goal-Seeking Agent

Generated by Amplihack Goal Agent Generator (Rust)
"""

import sys
from pathlib import Path
from typing import Any
{memory_import}
def main() -> int:
    """Run the goal-seeking agent."""
    print(f"Starting agent: {name}")
    print(f"SDK: {sdk}")
    print("Executing goal autonomously...")
    return 0


if __name__ == "__main__":
    sys.exit(main())
"#,
        name = bundle.name,
        sdk = bundle.sdk,
        memory_import = memory_import,
    )
}

pub(super) fn generate_readme(bundle: &AgentBundle) -> String {
    let memory_section = if bundle.memory_enabled {
        "\n## Memory\n\nThis agent has memory capabilities enabled.\n\
         Experiences are stored in the `./memory` directory.\n"
    } else {
        ""
    };

    let multi_agent_section = if bundle.multi_agent {
        "\n## Multi-Agent Architecture\n\nThis bundle uses a multi-agent setup:\n\
         - **coordinator**: Routes tasks to appropriate sub-agents\n\
         - **memory_agent**: Manages knowledge retrieval\n\
         - **spawner**: Dynamically creates specialist sub-agents\n\
         \nSee `sub_agents/` for configuration details.\n"
    } else {
        ""
    };

    format!(
        "# {name}\n\n\
         Goal: {goal}\n\n\
         Domain: {domain} | Complexity: {complexity}\n\n\
         ## Quick Start\n\n\
         ```bash\ncd {name}\npython main.py\n```\n\
         {memory_section}\
         {multi_agent_section}\n\
         ## Generated Metadata\n\n\
         - Bundle ID: {id}\n\
         - SDK: {sdk}\n\n\
         ---\n\nGenerated by Amplihack Goal Agent Generator (Rust)\n",
        name = bundle.name,
        goal = bundle.goal_def.goal,
        domain = bundle.goal_def.domain,
        complexity = bundle.goal_def.complexity,
        id = bundle.id,
        sdk = bundle.sdk,
    )
}

pub(super) fn generate_requirements(bundle: &AgentBundle) -> String {
    let mut reqs = vec!["amplihack>=0.9.0".to_string()];
    if bundle.memory_enabled {
        reqs.push("amplihack-memory-lib>=0.1.0".to_string());
    }
    if bundle.multi_agent {
        reqs.push("pyyaml>=6.0".to_string());
    }
    let mut s = reqs.join("\n");
    s.push('\n');
    s
}

// ---------------------------------------------------------------------------
// YAML template helpers
// ---------------------------------------------------------------------------

pub(super) fn coordinator_yaml(agent_name: &str) -> String {
    format!(
        "# Coordinator Configuration for {agent_name}\n\
         # Routes tasks to appropriate sub-agents based on classification\n\n\
         role: task_classifier\n\
         agent_name: \"{agent_name}\"\n\n\
         strategies:\n\
         \x20 - entity_centric\n\
         \x20 - temporal\n\
         \x20 - aggregation\n\
         \x20 - full_text\n\
         \x20 - simple_all\n\
         \x20 - two_phase\n\n\
         classification:\n\
         \x20 default_strategy: simple_all\n\
         \x20 confidence_threshold: 0.6\n"
    )
}

pub(super) fn memory_agent_yaml(agent_name: &str) -> String {
    format!(
        "# Memory Agent Configuration for {agent_name}\n\
         # Specializes in knowledge retrieval and fact management\n\n\
         role: retrieval_specialist\n\
         agent_name: \"{agent_name}\"\n\n\
         max_facts: 300\n\
         summarization_threshold: 1000\n\n\
         retrieval:\n\
         \x20 strategies:\n\
         \x20   - semantic_search\n\
         \x20   - keyword_match\n\
         \x20   - recency_weighted\n\
         \x20 max_results: 20\n\
         \x20 min_relevance: 0.3\n\n\
         memory_sharing:\n\
         \x20 read_access: true\n\
         \x20 write_access: false\n\
         \x20 namespace: \"{agent_name}-shared\"\n"
    )
}

pub(super) fn spawner_yaml(agent_name: &str, enabled: bool) -> String {
    format!(
        "# Spawner Configuration for {agent_name}\n\
         # Manages dynamic creation of specialist sub-agents\n\n\
         enabled: {enabled}\n\
         agent_name: \"{agent_name}\"\n\n\
         specialist_types:\n\
         \x20 - retrieval\n\
         \x20 - analysis\n\
         \x20 - synthesis\n\
         \x20 - code_generation\n\
         \x20 - research\n\n\
         max_concurrent: 3\n\
         timeout: 60\n\n\
         lifecycle:\n\
         \x20 auto_cleanup: true\n\
         \x20 idle_timeout: 30\n\
         \x20 max_memory_mb: 512\n\
         \x20 max_tokens_per_turn: 4096\n"
    )
}

pub(super) fn memory_config_yaml(agent_name: &str) -> String {
    format!(
        "# Memory Configuration for {agent_name}\n\n\
         agent_name: \"{agent_name}\"\n\
         storage_path: \"./memory\"\n\
         max_experiences: 1000\n\
         auto_compress: true\n"
    )
}

pub(super) fn multi_agent_init_py(agent_name: &str) -> String {
    format!(
        "\"\"\"Multi-agent initialization for {agent_name}.\"\"\"\n\n\
         AGENT_NAME = \"{agent_name}\"\n"
    )
}
